Atualizar o build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -20,11 +20,11 @@ jobs:
         with:
           python-version: "3.11"
 
-      - name: Configurar Java 11 (Compatível com o Gradle do Kivy)
+      - name: Configurar Java 17
         uses: actions/setup-java@v4
         with:
           distribution: "temurin"
-          java-version: "11"
+          java-version: "17"
 
       - name: Instalar ferramentas do sistema
         run: |
@@ -59,17 +59,13 @@ jobs:
           unset ANDROID_NDK_LATEST_HOME
           export GRADLE_OPTS="-Dorg.gradle.jvmargs=-Xmx2048m -Dorg.gradle.daemon=false"
           
-          set +e
-          buildozer -v android debug 2>&1 | tee build_raw.log
-          STATUS=$?
-          
-          if [ $STATUS -ne 0 ]; then
+          buildozer -v android debug > build.log 2>&1 || {
             echo ""
             echo "==================== [ERRO REAL DO GRADLE] ===================="
-            grep -B 45 "# Command failed:" build_raw.log || tail -n 45 build_raw.log
+            grep -B 40 "# Command failed:" build.log || tail -n 45 build.log
             echo "==============================================================="
-            exit $STATUS
-          fi
+            exit 1
+          }
 
       - name: Enviar APK gerado para Artifacts
         uses: actions/upload-artifact@v4
